name: Run tests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
